# Generated by Django 4.2.11 on 2026-03-05 06:07
from django.db import migrations

def seed_movies(apps, schema_editor):
    Movie = apps.get_model('bookings', 'Movie')
    Movie.objects.create(
        title="My Neighbor Totoro",
        description="Two sisters discover magical creatures in rural Japan.",
        release_date="1988-04-16",
        duration=86
    )
    Movie.objects.create(
        title="Everything Everywhere All at Once",
        description="A woman discovers she must connect with parallel universe versions of herself.",
        release_date="2022-03-25",
        duration=139
    )
    Movie.objects.create(
        title="Ratatouille",
        description="A rat who dreams of becoming a chef in Paris.",
        release_date="2007-06-29",
        duration=111
    )
    Movie.objects.create(
        title="Nacho Libre",
        description="A monk moonlights as a luchador wrestler to fund his orphanage.",
        release_date="2006-06-16",
        duration=92
    )
    Movie.objects.create(
        title="Interstellar",
        description="A team of explorers travel through a wormhole in space.",
        release_date="2014-11-07",
        duration=169
    )
    Movie.objects.create(
        title="Kung Fu Panda 2",
        description="Po and the Furious Five face a new villain threatening kung fu.",
        release_date="2011-05-26",
        duration=90
    )

def seed_superuser(apps, schema_editor):
    from django.contrib.auth.models import User
    if not User.objects.filter(username='admin').exists():
        User.objects.create_superuser(
            username='admin',
            password='admin123!',
            email=''
        )

class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(seed_movies),
        migrations.RunPython(seed_superuser),
    ]
